pipeline_space:
  val_split:
    type: float
    lower: 0.1
    upper: 0.33
  iqr_scale:
    type: float
    lower: 1
    upper: 2
  n_estimators:
    type: int
    lower: 50
    upper: 250
  criterion:
    choices: ["squared_error", "friedman_mse", "poisson"]
  max_depth:
    type: int
    lower: 5
    upper: 35